In [1]:
import numpy as np

# 1. Create 1D array
arr_1d = np.array([1, 2, 3, 4, 5, 6])
print(f"Original 1D Array:\n{arr_1d}\n")

# 2. Convert 1D array to 2D
arr_2d = arr_1d.reshape(2, 3)
print(f"1D Array converted to 2D:\n{arr_2d}\n")

# 3. Print Array Attributes
print("Array Attributes:")
print(f"Shape: {arr_2d.shape}")
print(f"Dimensions: {arr_2d.ndim}")
print(f"Data Type: {arr_2d.dtype}")
print(f"Item Size (bytes): {arr_2d.itemsize}\n")

# 4. Create a 3x3 NumPy array of all 9
arr_all_9 = np.full((3, 3), 9)
print(f"3x3 Array of all 9s:\n{arr_all_9}\n")

# 5. Create a 1D array of 10 evenly spaced values between 25 and 125
arr_linspace = np.linspace(25, 125, 10)
print(f"1D Array of 10 evenly spaced values between 25 and 125:\n{arr_linspace}\n")

# 6. Convert a Python list into a NumPy array
python_list = [10, 20, 30, 40, 50]
numpy_from_list = np.array(python_list)
print(f"Python list converted to NumPy array:\n{numpy_from_list}\n")

# 7. Reverse a 1D NumPy array
arr_to_reverse = np.array([1, 2, 3, 4, 5])
reversed_arr = arr_to_reverse[::-1]
print(f"Original array for reversal: {arr_to_reverse}")
print(f"Reversed 1D NumPy array: {reversed_arr}\n")

# 8. Create a 4x4x3 array and extract value at its second set, first row and last column
arr_3d = np.arange(1, 49).reshape(4, 4, 3) # Creating a sample 4x4x3 array
print(f"Original 4x4x3 array:\n{arr_3d}\n")
extracted_value = arr_3d[1, 0, -1] # second set (index 1), first row (index 0), last column (index -1)
print(f"Value at second set, first row, last column: {extracted_value}\n")

# 9. Create a 4x4 and Extract Odd Rows and Even Columns
arr_4x4 = np.arange(1, 17).reshape(4, 4)
print(f"Original 4x4 array:\n{arr_4x4}\n")
# Rows are 0-indexed, so odd rows are at indices 0 and 2
# Columns are 0-indexed, so even columns are at indices 1 and 3
extracted_rows_cols = arr_4x4[::2, 1::2]
print(f"Extracted Odd Rows (0, 2) and Even Columns (1, 3):\n{extracted_rows_cols}\n")

# 10. Slice the first two rows and first two columns of the second set from a 4x4x3 array
# Reusing arr_3d from step 8
sliced_3d_array = arr_3d[1, :2, :2] # second set (index 1), first two rows (:2), first two columns (:2)
print(f"Sliced first two rows and first two columns of the second set from 4x4x3 array:\n{sliced_3d_array}\n")

# 11. Replace all odd numbers in a NumPy array with -1 by iterating using a for loop
original_array = np.array([[23, 56, 78, 93], [71, 82, 13, 24]])
print(f"Original array for odd number replacement:\n{original_array}\n")

modified_array = original_array.copy() # Create a copy to avoid modifying the original directly
for i in range(modified_array.shape[0]):
    for j in range(modified_array.shape[1]):
        if modified_array[i, j] % 2 != 0:
            modified_array[i, j] = -1
print(f"Array after replacing odd numbers with -1:\n{modified_array}\n")

# 12. Get the indices of non-zero elements in an array [1, 0, 2, 0, 3, 0, 4]
arr_non_zero = np.array([1, 0, 2, 0, 3, 0, 4])
indices_non_zero = np.nonzero(arr_non_zero)
print(f"Original array for non-zero indices: {arr_non_zero}")
print(f"Indices of non-zero elements: {indices_non_zero}\n")

# 13. Perform arithmetic operations on two NumPy arrays element-wise
arr_a = np.array([[1, 2], [3, 4]])
arr_b = np.array([[5, 6], [7, 8]])
print(f"Array A:\n{arr_a}")
print(f"Array B:\n{arr_b}\n")

# Add two NumPy arrays element by element
arr_sum = arr_a + arr_b
print(f"Element-wise addition:\n{arr_sum}\n")

# Multiply two NumPy arrays element by element
arr_product = arr_a * arr_b
print(f"Element-wise multiplication:\n{arr_product}\n")

# 14. Write a code to compute the dot product of two NumPy arrays
arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])
print(f"Array 1 for dot product: {arr1}")
print(f"Array 2 for dot product: {arr2}\n")

dot_product = np.dot(arr1, arr2)
print(f"Dot product of arr1 and arr2: {dot_product}\n")


Original 1D Array:
[1 2 3 4 5 6]

1D Array converted to 2D:
[[1 2 3]
 [4 5 6]]

Array Attributes:
Shape: (2, 3)
Dimensions: 2
Data Type: int64
Item Size (bytes): 8

3x3 Array of all 9s:
[[9 9 9]
 [9 9 9]
 [9 9 9]]

1D Array of 10 evenly spaced values between 25 and 125:
[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]

Python list converted to NumPy array:
[10 20 30 40 50]

Original array for reversal: [1 2 3 4 5]
Reversed 1D NumPy array: [5 4 3 2 1]

Original 4x4x3 array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]
  [46 47 48]]]

Value at second set, first row, last column: 15

Original 4x4 array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Extracted Odd Rows (0, 2) and Even Columns (1, 3):
[[ 2  4]
 [10 12]]

Sliced first two ro