In [32]:
#1) Combining a one and a two-dimensional NumPy Array
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([
    [4, 5, 6],
    [7, 8, 9]
])   
arr1_2d = arr1.reshape(1, 3)
combined = np.vstack((arr1_2d, arr2))
print(combined)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#2) Flatten a 2d numpy array into 1d array
import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
flat = arr.flatten()
print(flat)

[1 2 3 4 5 6]


In [ ]:
#3) Reverse a numpy array
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
rev = arr[::-1]
print(rev)

[50 40 30 20 10]


In [ ]:
#4) Practice operations like Get the maximum value from given array Get the minimum value from given array Find the number of rows and columns of a given array using NumPy Select the elements from a given array (each element and specific element) Find the sum of values in a 2D array using for loop Adding, Subtracting, multiplying, dividing arrays in Numpy 
#Maximum Value
import numpy as np

arr = np.array([3, 7, 2, 9, 5])
print(np.max(arr))

9


In [17]:
#Minimum Value
print(np.min(arr))

2


In [19]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
rows = arr.shape[0]
cols = arr.shape[1]

print("Rows =", rows)
print("Columns =", cols)

Rows = 2
Columns = 3


In [20]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr)
print(arr[1, 2])

[[10 20 30]
 [40 50 60]]
60


In [ ]:
# 5) Iterate 3D array using for loop and nditer 
import numpy as np

arr = np.array([
    [1, 2],
    [3, 4]
])
total = 0
for row in arr:
    for value in row:
        total += value

print("Sum =", total)

Sum = 10


In [25]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


In [27]:
import numpy as np
arr = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8


In [31]:
# 6) Study the following program import numpy as np # create a numpy 1d-arrays arr1 = np.array([3, 4]) arr2 = np.array([1, 0]) # find average of NumPy arrays avg = (arr1 + arr2) / 2 print("Average of NumPy arrays:\n", avg) -> Calculate average mean median mode values of two NumPy 2d-arrays
import numpy as np

arr1 = np.array([
    [1, 2],
    [3, 4]
])
arr2 = np.array([
    [5, 6],
    [7, 8]
])

avg = (arr1 + arr2) / 2

print("Average Array:")
print(avg)

mean_value = np.mean(avg)
print("Mean =", mean_value)

median_value = np.median(avg)
print("Median =", median_value)

flat = avg.flatten()
values, counts = np.unique(flat, return_counts=True)
mode_value = values[np.argmax(counts)]
print("Mode =", mode_value)


Average Array:
[[3. 4.]
 [5. 6.]]
Mean = 4.5
Median = 4.5
Mode = 3.0
