In [ ]:
# q1 Replace Nan with 0 and Interchange 3 rows and 3 columns of 2D array [[6, -8, 73, -110], [np.nan, -8, 0, 94]]
import numpy as np
arr = np.array([[6, -8, 73, -110], [np.nan, -8, 0, 94]])
print(arr)
arr = np.nan_to_num(arr ,nan =0)
print("\nAfter replacing NaN with 0:")
print(arr)

arr = arr.T
print("\n After Interchanging rows and columns:")
print(arr)


[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]

After replacing NaN with 0:
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]

 After Interchanging rows and columns:
[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [ ]:
#q2 Move axes of 3D array to new positions 

import numpy as np

arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print("Original Array Shape: ",arr.shape)
print(arr)

new_arr = np.moveaxis(arr,[0,1,2],[2,0,1])

print("\nNew Array Shape:",new_arr.shape)
print(new_arr)

Original Array Shape:  (2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

New Array Shape: (2, 2, 2)
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [ ]:
#q3 Replace NaN values with average of columns

import numpy as np
arr = np.array([[1,2,np.nan],
                [4,np.nan,6],
                [7,8,9]])
print("Original Array:")
print(arr)

col_mean = np.nanmean(arr,axis = 0)
inds = np.where(np.isnan(arr))

arr[inds] = np.take(col_mean, inds[1])
print("\nArray after replacing NaN with columns averages:")
print(arr)



Original Array:
[[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]

Array after replacing NaN with columns averages:
[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [ ]:
#q4 Replace negative value with zero in numpy array using replace
import numpy as np

arr = np.array([[6,-8,73],
                [-5,0,-2]])

arr[arr<0] = 0
print(arr)

[[ 6  0 73]
 [ 0  0  0]]


In [18]:
import numpy as np
arr = np.array([[6,-8,73],
                [-5,0,-2]])
new_arr = np.where(arr<0,0,arr)
print(new_arr)

[[ 6  0 73]
 [ 0  0  0]]
